add function and parameters

diff --git a/sys_info_page b/sys_info_page
--- a/sys_info_page
+++ b/sys_info_page
@@ -1,6 +1,9 @@
 #!/bin/bash
 
-# Program to output a system information page
+# sys_info_page: Program to output a system information page
+
+PROGNAME=$(basename $0)
+
 TITLE="System Information Report For $HOSTNAME"
 CURRENT_TIME=$(date +"%x %r %Z")
 TIME_STAMP="Generated $CURRENT_TIME, by $USER"
@@ -22,25 +25,99 @@ report_disk_space () {
 }
 
 report_home_space () {
-	cat <<- _EOF_
-		<H2>Home Space Utilization</H2>
-		<PRE>$(du -sh /home/*)</PRE>
-		_EOF_
+	if [[ $(id -u) -eq 0 ]]; then
+		cat <<- _EOF_
+			<H2>Home Space Utilization (All Users)</H2>
+			<PRE>$(du -sh /home/*)</PRE>
+			_EOF_
+	else
+		cat <<- _EOF_
+			<H2>Home Space Ultilization ($USER)</H2>
+			<PRE>$(du -sh $HOME)</PRE>
+			_EOF_
+	fi
 	return
 }
 
+usage () {
+	echo "$PROGNAME: usage: $PROGNAME [ -f file | -i ]"
+	return
+}
 
-cat << _EOF_
-<HTML>
-	<HEAD>
-		<TITLE>$TITLE</TITLE>
-	</HEAD>
-	<BODY>
-		<H1>$TITLE</H1>
-		<P>$TIME_STAMP</P>
-		$(report_uptime)
-		$(report_disk_space)
-		$(report_home_space)
-	</BODY>
-</HTML>"
-_EOF_
+write_html_page () {
+	cat <<- _EOF_
+	<HTML>
+		<HEAD>
+			<TITLE>$TITLE</TITLE>
+		</HEAD>
+		<BODY>
+			<H1>$TITLE</H1>
+			<P>$TIME_STAMP</P>
+			$(report_uptime)
+			$(report_disk_space)
+			$(report_home_space)
+		</BODY>
+	</HTML>
+	_EOF_
+	return
+}
+
+# process command line options
+
+interactive=
+filename=
+
+while [[ -n $1 ]]; do # 只要位置参数$1不为空,则循环继续
+	case $1 in 
+		-f | --file)		shift     #使位置参数$1的内容							#置换为-f选项后的文件名
+					filename=$1
+					;;
+		-i | --interactive)	interactive=1
+					;;
+		-h | --help)		usage
+					exit
+					;;
+		*)			usage >$2 #如果没有发现匹配项
+						  #输出程序使用信息
+					exit 1    #脚本以erro结束运行
+					;;
+	esac
+	shift
+done
+
+# interactive mode
+
+if [[ -n $interactive ]]; then # 如果interactive变量不为空，开启一个无限循环
+	while true; do
+		read -p "Enter name of output file: " filename
+		if [[ -e $filename ]]; then
+			read -p "'$filename' exists. Overwrite? [y/n/q] > "
+			case $REPLY in 
+				Y|y)	break
+					;;
+				Q|q)	echo "Program terminated."
+					exit
+					;;
+				*)	continue
+					;;
+			esac
+		elif [[ -z $filename ]]; then
+			continue
+		else
+			break
+		fi
+	done
+fi
+
+# output html page
+
+if [[ -n $filename ]]; then
+	if touch $filename && [[ -f $filename ]]; then # touch命令失败的话说明输入的是无效路径
+		write_html_page > $filename
+	else
+		echo "$PROGRAM: Cannot write file '$filename'" >&2
+		exit 1
+	fi
+else
+	write_html_page
+fi
